### ISSUE TITLE
problem parsing multi-line definition

### ISSUE THREAD

**Issue by EtlamGit** [Jiangshan00001/pyvcdr#1]
Most VCD files I have, use a multi-line definition for each timestamp:
```
#1
b00 !
b1100 "
#2
b11 !
b1110 "
```
You mentioned [PyVCD](https://github.com/westerndigitalcorporation/pyvcd), the example of that VCD writer also generates that kind of format.

**Comment by EtlamGit** [comment]
When looking into your code, I notice that you only parse for `$command` and `#time_value`.
The third option would be a line not starting with $ or #. e.g. to call a new function process_signal_change() in that case. You would also have to remember the last valid time definition to have it available for that function.

process_time_value has to learn parsing time definitions without signal change.
In case there is also a signal change (like in your test1.vcd) you could call the new function on the rest of the line.

**Comment by Jiangshan00001** [comment]
@EtlamGit i changed the code.
It should work for you.
just try and tell me the result.
BTW:  you should download the code from github. I have not updated the pypi.

**Comment by EtlamGit** [comment]
Great, very fast reaction.
Now it is working better, but fails in your new check routine in line 124.

My VCD files use a syntax for single bit signals to omit the space:
```
#1
b011011010100 c
b011101010101 f
1j
0k
0o
1p
#2
b011010100010 c
b011101110001 f
0l
1o
```
so there is the space you expect in case of wider signals, but it is missing for 1-bit-wide signals.


(I always use the code directly from here, installation via pip and package seems to be broken currently. I will open another issue or even pull request when I'm able to figure out why this is the case.)

**Comment by Jiangshan00001** [comment]
I changed the code. it may work for you now.
if not. could you upload the full vcd file so that I could test it.
@EtlamGit

**Comment by EtlamGit** [comment]
Very nice, a first short test seems to work well now.

I will do some more tests with larger files next week.
